### PR TITLE
all commands refactored to support tab-completion except for regionFlag

### PR DESCRIPTION
**Pull request by eheimer**
I hope I did this right!  I come from subversion, so git is new to me.  I followed this guide: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/
and only screwed it up once and had to start over.  As far as the regionFlag command goes, it is more complex because the options for the second <flag> argument needs to be built based on what the user selected for the first <subFlag> argument.  I have an idea of how this can be done, but I'm not sure where is the best place to have that discussion.

Any feedback is welcome.  Thanks for giving me the chance to contribute.

### CODE REVIEW

**Comment by Brycey92** [comment]
I'm only semi-familiar with git, and have had to restart projects many times due to messing things up. It's all part of the initiation, I guess. I'll take a look at your code in a minute here, and I suppose the best place to have the discussion would be in this PR thread.

**Comment by eheimer** [comment]
In that case...

command in question:
`/rg flag <subFlag> <flag> <value>`

As far as I can tell from the code and wiki, the `<flag>` argument should be a subset determined by what was specified in the `<subFlag>` argument.  Poring through the Sponge api documentation, I did not see a way in the CommandSpec to base the command completion off of another argument.

So the simplest way to make the completion work, I think, is to make each of the subFlags a child command of the `/rg flag` command.  I haven't analyzed your code enough to know what other areas that might affect, or what issues might come up.  If you want, I can start refactoring see if it really is that simple.

**Comment by JimiIT92** [comment]
Yes, unfortunately Sponge has no simple way to tell a command what is it's subset for tab completition (at least from what i know). I'm merging and testing right now your features, if all works correctly that will be a really huge step for the plugin and i can't thank you enough for this :D

**Comment by JimiIT92** [comment]
PS: I'm pretty new to Git and versioning too, so i guess we are all learning something here 😅 By the way i'll try to make a universal version, something built with API7 that will work in 1.10.2 also, so there will be only one project to work on and not two as by now :) The repo for that version will be the API6 repo, since it contains the Wiki already :)

**Comment by eheimer** [comment]
Sounds good.  I'm glad I could help out!  So should I continue to work off of the API7 project, or should I hold off for the universal version?

**Comment by JimiIT92** [comment]
No, the API7 project will be the main project but it will eventually be moved to the other repository :) Also i think i've figured out how to do tab completitions for the flag command without changing it :D I'll commit my changes to give you an idea (will stil not work)

**Comment by JimiIT92** [comment]
Commited right now, there are 2 new elements: boolean for handling boolean values (the Sponge default one was buggy, it show values like "0", "from", and other stuffs) and subflag to give the list of subflags (wich are now stored into an enum)

**Comment by eheimer** [comment]
Yeah, I had noticed that goofiness with the booleans.  Your solution is much better.  I see what you did with the subflags.  Seems like that might work.  I'll play with it this evening.  I was planning on putting the subflags into an enum as well.  You beat me to it.  :)

**Comment by JimiIT92** [comment]
I don't know why the Sponge's standard boolean list is that messed up. By the way i'm glad you had the same idea for the Subflag, that means we are on the same frequency :D I'm testing right now if the flag command element works, to return a different list based on the subflag. If it works there will be only the setspawn and settp commands to handle, since location list is messed up too :)

**Comment by JimiIT92** [comment]
Update: the flag list itself works, even when handling mob id's. However i can't figure out how to return a different list based on subflag. So i guess the best way to do this is to split the region flag command into some subcommands, like "/rg mobflag" to set mobflags, "/rg interactflag" to set interacts and so on... I'll wait before doing this since i want to know if you have an idea of how to achieve this without splitting the command :)

**Comment by eheimer** [comment]
Regarding location, I had noticed that was messed up too, but I wasn't sure how it should work and then I forgot about it.  Thinking about it now, maybe [TAB] should just auto-fill the player's current location, formatted properly like (x,y,z)?  That would at least show the player what the correct format should be and they can change the numbers manually if they want.  Probably 9 times out of 10 that will be what they want anyway.

**Comment by JimiIT92** [comment]
Yes, the easiest way will be to show the exact coordinates. The best way would be to use relative coordinates like mc commands does, but maybe that requires a lot of work to do :) Let's see if it works with absolute coordinates first :)

**Comment by eheimer** [comment]
This is probably just my minecraft ignorance showing through.  What do you mean by relative coordinates (relative to what?) and which minecraft commands use relative coordinates?

**Comment by JimiIT92** [comment]
Relative coordinates are values like ~. These are used by commands like the tp command, if you do ~3 as X coordinate it will take the player X coordinate + 3. But i don't know if in Sponge there is a way (like in Forge) to convert these coordinates into real numbers

**Comment by eheimer** [comment]
Oh cool.  I learned something new.  :)

**Pull request merged**
